Repository nusmodifications/nusmods, pull requests merged in 2020-10, with the labels that each got.

#2792 Improve edge case handling for module credits, exam duration and floor numbers
  scrapers/nus-v2/swagger.yaml
  website/src/utils/modules.test.ts
  website/src/utils/modules.ts
  website/src/views/components/module-info/ModuleExamInfo.tsx
  website/src/views/modules/ModulePageContent.tsx
  website/src/views/timetable/ModulesTableFooter.tsx
  website/src/views/venues/VenueLocation/ImproveVenueForm.tsx
Labels: automerge

#2918 Remove unused js-combinatorics
  website/package.json
  website/yarn.lock
Labels: automerge, better engineering

#2784 Indexed covid zones in scraper to enable faceted search on modules page
  scrapers/nus-v2/package.json
  scrapers/nus-v2/src/services/__mocks__/getCovidZones.ts
  scrapers/nus-v2/src/services/__mocks__/getVenueLocations.ts
  scrapers/nus-v2/src/services/__mocks__/nus-api.ts
  scrapers/nus-v2/src/services/getCovidZones.ts
  scrapers/nus-v2/src/services/getVenueLocations.ts
  scrapers/nus-v2/src/services/io/elastic.ts
  scrapers/nus-v2/src/services/nus-api.ts
  scrapers/nus-v2/src/tasks/CollateModules.test.ts
  scrapers/nus-v2/src/tasks/CollateModules.ts
  scrapers/nus-v2/src/tasks/CollateVenues.test.ts
  scrapers/nus-v2/src/tasks/CollateVenues.ts
  scrapers/nus-v2/src/tasks/DataPipeline.test.ts
  scrapers/nus-v2/src/tasks/GetSemesterData.test.ts
  scrapers/nus-v2/src/tasks/GetSemesterData.ts
  scrapers/nus-v2/src/tasks/GetSemesterTimetable.test.ts
  scrapers/nus-v2/src/tasks/GetSemesterTimetable.ts
  scrapers/nus-v2/src/tasks/MigrateV1ToV2.ts
  scrapers/nus-v2/src/tasks/fixtures/expected/CS2100.json
  scrapers/nus-v2/src/types/modules.ts
  scrapers/nus-v2/src/types/venues.ts
  scrapers/nus-v2/src/utils/data.test.ts
  scrapers/nus-v2/src/utils/set.ts
  scrapers/nus-v2/tsconfig.json
  scrapers/nus-v2/yarn.lock
  website/src/views/modules/ModuleFinderContainer/ModuleFinderContainer.tsx
  website/src/views/modules/ModuleFinderSidebar.tsx
Labels: automerge

#2921 Fix vertical timetable cell layout
  website/src/views/timetable/TimetableCell.scss
Labels: automerge

#2919 Speed up prod-deploy by allowing blue to build from cache
  prod-deploy.sh
Labels: automerge, better engineering

#2932 Update sitemap
  website/static/sitemap.txt
Labels: automerge

#2931 Fix skipped public holidays in holiday scraper
  website/scripts/holidays/2019_singapore_holidays.csv
  website/scripts/holidays/2020_singapore_holidays.csv
  website/scripts/holidays/2021_singapore_holidays.csv
  website/scripts/public-holidays-ics-to-csv.js
Labels: automerge, bug
