Repository nusmodifications/nusmods, pull requests merged in 2020-12, with the labels that each got.

#3007 Remove `withRouter` (1/n)
  renovate.json
  website/jest.common.config.js
  website/package.json
  website/scripts/test.js
  website/src/.eslintrc.js
  website/src/actions/venueBank.ts
  website/src/bootstrapping/configure-store.ts
  website/src/bootstrapping/sentry.ts
  website/src/entry/main.tsx
  website/src/test-utils/mockDom.ts
  website/src/types/global.d.ts
  website/src/utils/css.ts
  website/src/utils/react.tsx
  website/src/views/AppShell.tsx
  website/src/views/components/KeyboardShortcuts.tsx
  website/src/views/components/RandomKawaii.tsx
  website/src/views/components/ScrollToTop.test.tsx
  website/src/views/components/ScrollToTop.tsx
  website/src/views/components/module-info/LessonTimetable.tsx
  website/src/views/components/module-info/SemesterPicker.tsx
  website/src/views/components/notfications/ModRegNotification.tsx
  website/src/views/contribute/ContributeContainer/ContributeContainer.tsx
  website/src/views/hocs/makeResponsive.tsx
  website/src/views/hooks/useMediaQuery.ts
  website/src/views/hooks/useScrollToTop.test.tsx
  website/src/views/hooks/useScrollToTop.ts
  website/src/views/layout/GlobalSearchContainer.test.tsx
  website/src/views/layout/GlobalSearchContainer.tsx
  website/src/views/modules/ModulePageContent.tsx
  website/src/views/settings/SettingsContainer.tsx
  website/src/views/static/StaticPage.tsx
  website/src/views/timetable/TimetableContainer.tsx
  website/webpack/webpack.config.dev.js
  website/webpack/webpack.config.prod.js
  website/webpack/webpack.config.timetable-only.js
  website/yarn.lock
Labels: automerge

#3025 Add tests for `useMediaQuery` hook
  website/src/types/views.ts
  website/src/views/hocs/makeResponsive.tsx
  website/src/views/hooks/useMediaQuery.test.tsx
  website/src/views/hooks/useMediaQuery.ts
  website/src/views/layout/GlobalSearchContainer.test.tsx
Labels: automerge

#3042 Refactor to use FC and useMediaQuery [SideMenuComponent]
  website/src/views/components/SideMenu.tsx
Labels: automerge

#3059 Fix uncaught promise rejection in actions/moduleBank.test.ts
  website/src/actions/moduleBank.test.ts
Labels: better engineering

#3067 Remove deprecated V1 NUS scraper
  .circleci/config.yml
  renovate.json
  scrapers/nus/.babelrc
  scrapers/nus/.env.example
  scrapers/nus/.htaccess
  scrapers/nus/README.md
  scrapers/nus/__mocks__/.eslintrc.js
  scrapers/nus/__mocks__/bunyan.js
  scrapers/nus/__mocks__/fixtures/examData1.json
  scrapers/nus/__mocks__/fixtures/examData2.json
  scrapers/nus/__mocks__/fixtures/test1.pdf
  scrapers/nus/__mocks__/fixtures/test2.pdf
  scrapers/nus/config.js
  scrapers/nus/gulp-tasks/index.js
  scrapers/nus/gulp-tasks/local/consolidateForSem.js
  scrapers/nus/gulp-tasks/local/consolidateForYear.js
  scrapers/nus/gulp-tasks/local/genReqTree/constants.js
  scrapers/nus/gulp-tasks/local/genReqTree/index.js
  scrapers/nus/gulp-tasks/local/genReqTree/normalizeString.js
  scrapers/nus/gulp-tasks/local/genReqTree/normalizeString.test.js
  scrapers/nus/gulp-tasks/local/genReqTree/parse+normalize.test.js
  scrapers/nus/gulp-tasks/local/genReqTree/parseString.js
  scrapers/nus/gulp-tasks/local/genReqTree/parseString.test.js
  scrapers/nus/gulp-tasks/local/mergeCorsBiddingStats.js
  scrapers/nus/gulp-tasks/local/splitForSem.js
  scrapers/nus/gulp-tasks/local/splitForYear.js
  scrapers/nus/gulp-tasks/remote/__snapshots__/examTimetable.test.js.snap
  scrapers/nus/gulp-tasks/remote/bulletinModules.js
  scrapers/nus/gulp-tasks/remote/cors.js
  scrapers/nus/gulp-tasks/remote/corsBiddingStats.js
  scrapers/nus/gulp-tasks/remote/examTimetable.js
  scrapers/nus/gulp-tasks/remote/examTimetable.test.js
  scrapers/nus/gulp-tasks/remote/ivle.js
  scrapers/nus/gulp-tasks/remote/moduleTimetableDelta.js
  scrapers/nus/gulp-tasks/remote/venues.js
  scrapers/nus/gulp-tasks/utils/__snapshots__/timify.test.js.snap
  scrapers/nus/gulp-tasks/utils/gotCached.js
  scrapers/nus/gulp-tasks/utils/iterateSems.js
  scrapers/nus/gulp-tasks/utils/mergeModuleFields.js
  scrapers/nus/gulp-tasks/utils/mergeModuleFields.test.js
  scrapers/nus/gulp-tasks/utils/pdf.js
  scrapers/nus/gulp-tasks/utils/pdf.test.js
  scrapers/nus/gulp-tasks/utils/sortByKey.js
  scrapers/nus/gulp-tasks/utils/sortByKey.test.js
  scrapers/nus/gulp-tasks/utils/timify.js
  scrapers/nus/gulp-tasks/utils/timify.test.js
  scrapers/nus/gulp-tasks/utils/titleize.js
  scrapers/nus/gulpfile.babel.js
  scrapers/nus/jest.config.js
  scrapers/nus/jsonp.php
  scrapers/nus/package.json
  scrapers/nus/webpack.config.babel.js
  scrapers/nus/yarn.lock
Labels: api

#3070 Remove eslint-loader and stylelint-webpack-loader
  website/README.md
  website/package.json
  website/webpack/webpack.config.dev.js
  website/webpack/webpack.parts.js
  website/yarn.lock
Labels: better engineering

#3092 Set up /website Vercel deployment
  website/Dockerfile.prod
  website/README.md
  website/scripts/build.js
  website/src/config/app-config.json
  website/vercel.json
  website/webpack/webpack.config.browser-warning.js
  website/webpack/webpack.config.common.js
  website/webpack/webpack.config.dev.js
  website/webpack/webpack.config.prod.js
  website/webpack/webpack.config.timetable-only.js
  website/webpack/webpack.parts.js
Labels: better engineering

#3095 Turn export service into a Vercel serverless function
  export/api/export/image.ts
  export/api/export/pdf.ts
  export/package.json
  export/public/404.html
  export/public/styles.css
  export/src/HttpError.ts
  export/src/data.ts
  export/src/handler.ts
  export/src/render-serverless.ts
  export/src/views.ts
  export/src/views/base.pug
  export/vercel.json
  export/yarn.lock
Labels: export

#3099 Point /website timetable export button to Vercel serverless function
  export/.env.example
  website/src/apis/export.ts
Labels: automerge

#3105 Truncate long exam duration string
  website/src/utils/modules.test.ts
  website/src/utils/modules.ts
Labels: bug, module page, user interface

#3107 Force version string date to be in SGT
  website/webpack/webpack.parts.js
Labels: automerge

#3106 Add Sentry performance monitoring and environments
  website/jest.common.config.js
  website/package.json
  website/src/.eslintrc.js
  website/src/bootstrapping/sentry.ts
  website/src/types/global.d.ts
  website/webpack/webpack.config.dev.js
  website/webpack/webpack.config.prod.js
  website/webpack/webpack.config.timetable-only.js
  website/yarn.lock
Labels: automerge, better engineering

#3104 Add subject to NBSP errors
  scrapers/nus-v2/src/services/logger/SentryStream.ts
  scrapers/nus-v2/src/tasks/GetSemesterModules.ts
  website/src/apis/github.ts
  website/src/bootstrapping/sentry.ts
  website/src/reducers/index.ts
  website/src/reducers/undoHistory.test.ts
  website/src/reducers/undoHistory.ts
Labels: api, automerge
