Repository nusmodifications/nusmods, pull requests merged in 2020-05, with the labels that each got.

#2626 Speed up CI by disabling node_modules cache
  .circleci/config.yml
Labels: better engineering

#2628 Migrate JS function components to const React.FC
  website/src/views/components/ButtonGroupSelector.tsx
  website/src/views/components/CloseButton.tsx
  website/src/views/components/ExternalLink.tsx
  website/src/views/components/Fab.tsx
  website/src/views/components/Omelette.tsx
  website/src/views/components/Title.tsx
  website/src/views/components/map/LocationMap.tsx
  website/src/views/contribute/ContributorList.tsx
  website/src/views/errors/ErrorBoundary.test.tsx
  website/src/views/errors/NotFoundPage.tsx
  website/src/views/errors/Warning.tsx
  website/src/views/layout/Footer.tsx
  website/src/views/layout/Navtabs.tsx
  website/src/views/modules/ModuleTree.tsx
  website/src/views/planner/PlannerSettings.tsx
  website/src/views/routes/ExternalRedirect.tsx
  website/src/views/routes/Routes.tsx
  website/src/views/settings/ModeSelect.tsx
  website/src/views/settings/ThemeOption.tsx
  website/src/views/static/AboutContainer.tsx
  website/src/views/static/AppsContainer.tsx
  website/src/views/static/ContributorsContainer.tsx
  website/src/views/static/FaqContainer.tsx
  website/src/views/static/HacktoberfestContainer.tsx
  website/src/views/static/HacktoberfestLogo.tsx
  website/src/views/static/StaticPage.tsx
  website/src/views/static/TeamContainer.tsx
  website/src/views/tetris/overlays/GameOver.tsx
  website/src/views/tetris/overlays/GameOverlay.tsx
  website/src/views/tetris/overlays/GamePaused.tsx
  website/src/views/tetris/overlays/GameStart.tsx
  website/src/views/tetris/overlays/HighScoreTable.tsx
  website/src/views/tetris/overlays/TetrisLogo.tsx
  website/src/views/timetable/CurrentTimeIndicator.tsx
  website/src/views/timetable/ExamWeek.tsx
  website/src/views/timetable/ModuleTombstone.tsx
  website/src/views/timetable/ModulesTableFooter.tsx
  website/src/views/timetable/TimetableActions.tsx
  website/src/views/timetable/TimetableCell.tsx
  website/src/views/timetable/TimetableDay.tsx
  website/src/views/timetable/TimetableHighlight.tsx
  website/src/views/timetable/TimetableRow.tsx
  website/src/views/timetable/TimetableTimings.tsx
  website/src/views/today/BeforeLessonCard.tsx
  website/src/views/today/DayHeader.tsx
  website/src/views/today/TodayContainer/TodayContainer.tsx
  website/src/views/venues/VenueList.tsx
Labels: better engineering

#2629 Clean up website ESLint rules
  website/.eslintrc.js
  website/.postcssrc.js
  website/.stylelintrc.js
  website/scripts/build.js
  website/scripts/download-bus-stops.js
  website/src/.eslintrc.js
  website/src/bootstrapping/configure-store.ts
  website/src/data/academic-calendar.ts
  website/src/reducers/index.ts
  website/src/reducers/planner.test.ts
  website/src/reducers/requests.ts
  website/src/selectors/planner.ts
  website/src/storage/index.ts
  website/src/types/export.ts
  website/src/types/redux.ts
  website/src/utils/array.ts
  website/src/utils/colors.ts
  website/src/utils/elasticSearch.ts
  website/src/utils/error.ts
  website/src/utils/modules.ts
  website/src/utils/promise.ts
  website/src/utils/react.test.tsx
  website/src/views/components/Omelette.tsx
  website/src/views/components/disqus/DisqusComments.tsx
  website/src/views/components/map/BusStops.tsx
  website/src/views/components/map/icons.ts
  website/src/views/components/map/withVenueLocations.tsx
  website/src/views/components/notfications/Notification.tsx
  website/src/views/components/searchkit/Pagination.tsx
  website/src/views/contribute/ContributorList.tsx
  website/src/views/elements.js
  website/src/views/modules/ModuleFinderContainer/ModuleFinderContainer.tsx
  website/src/views/modules/ModulePageContainer.tsx
  website/src/views/tetris/ScrollingNumber.tsx
  website/src/views/tetris/TetrisGame.tsx
  website/src/views/tetris/board.ts
  website/src/views/timetable/TimetableContent.tsx
  website/src/views/today/TodayContainer/TodayContainer.tsx
  website/src/views/venues/VenueLocation/ImproveVenueForm.tsx
  website/src/views/venues/VenuesContainer.tsx
Labels: better engineering

#2664 Add automerge action
  .github/workflows/automerge.yml
Labels: automerge

#2663 Add tests for CommentCount
  website/src/views/components/disqus/CommentCount.test.tsx
  website/src/views/components/disqus/CommentCount.tsx
Labels: automerge, better engineering

#2650 Add Special Term start dates to academic-calendar.json
  website/src/data/academic-calendar.json
Labels: automerge
