Repository nusmodifications/nusmods, pull requests merged in 2021-01, with the labels that each got.

#3130 Correct Sentry env derivation from VERCEL_ENV
  website/src/bootstrapping/sentry.ts
Labels: bug

#3124 Remove unused deps from /website
  website/README.md
  website/package.json
  website/scripts/serve.js
  website/yarn.lock
Labels: automerge, better engineering

#3125 Bump scraper deps
  scrapers/nus-v2/package.json
  scrapers/nus-v2/src/services/logger/SentryStream.ts
  scrapers/nus-v2/src/services/logger/serializer.test.ts
  scrapers/nus-v2/src/services/requisite-tree/parseString.ts
  scrapers/nus-v2/src/services/validation.ts
  scrapers/nus-v2/src/types/v1.ts
  scrapers/nus-v2/yarn.lock
Labels: api

#3136 Minor build, lint, and CI fixes
  .circleci/config.yml
  netlify.toml
  scrapers/.eslintrc.js
  scrapers/nus-v2/.eslintrc.js
  website/.eslintrc.js
Labels: automerge

#3041 Replace `ScrollToTop` with `useScrollToTop`
  website/src/test-utils/renderWithRouterMatch.tsx
  website/src/views/components/ScrollToTop.tsx
  website/src/views/hooks/useMediaQuery.test.tsx
  website/src/views/hooks/useMediaQuery.ts
  website/src/views/modules/ModulePageContent.test.tsx
  website/src/views/modules/ModulePageContent.tsx
  website/src/views/settings/SettingsContainer.tsx
Labels: automerge

#3133 Update location data
  website/src/data/venues.json
Labels: automerge

#3131 Fix no scroll behavior on iOS
  website/package.json
  website/src/styles/components/loading-spinner.scss
  website/src/styles/layout/site.scss
  website/src/styles/main.scss
  website/src/utils/disableScrolling.test.ts
  website/src/utils/disableScrolling.ts
  website/src/views/components/Modal.tsx
  website/src/views/components/SearchkitSearchBox.scss
  website/src/views/components/SearchkitSearchBox.tsx
  website/src/views/components/SideMenu.scss
  website/src/views/components/SideMenu.tsx
  website/src/views/layout/Navtabs.scss
  website/yarn.lock
Labels: bug, user interface

#3137 Introduce `NUSMODS_ENV` and fix deploy preview robots.txt and Sentry env
  export/src/render-serverless.ts
  website/jest.common.config.js
  website/package.json
  website/src/.eslintrc.js
  website/src/bootstrapping/configure-store.ts
  website/src/bootstrapping/sentry.ts
  website/src/entry/main.tsx
  website/src/storage/persistReducer.ts
  website/src/types/global.d.ts
  website/src/views/modules/ReportError.tsx
  website/static/base/BingSiteAuth.xml
  website/static/base/QKxkGnstY5yNFJZlmSoAkmOPJzZVVc
  website/static/base/_redirects
  website/static/base/android-icon-192x192.png
  website/static/base/android-icon-512x512.png
  website/static/base/apple-icon-180x180.png
  website/static/base/favicon-16x16.png
  website/static/base/favicon-32x32.png
  website/static/base/google238cc1d8dc3a54bb.html
  website/static/base/manifest.json
  website/static/base/opensearch.xml
  website/static/base/safari-pinned-tab.svg
  website/static/base/service-worker.js
  website/static/base/sitemap.txt
  website/static/preview-and-staging-only/robots.txt
  website/static/production-only/robots.txt
  website/webpack/webpack.config.common.js
  website/webpack/webpack.config.dev.js
  website/webpack/webpack.config.prod.js
  website/webpack/webpack.config.timetable-only.js
  website/webpack/webpack.parts.js
  website/yarn.lock
Labels: bug

#3071 Bump query-string and enable transpilation of it
  renovate.json
  website/package.json
  website/src/utils/debug.ts
  website/src/utils/timetables.ts
  website/src/views/venues/VenuesContainer.tsx
  website/webpack/webpack.config.common.js
  website/yarn.lock
Labels: better engineering
