Repository nusmodifications/nusmods, pull requests merged in 2025-07, with the labels that each got.

#4083 Resolve optimiser free day conflicts
  .gitignore
  website/README.md
  website/src/views/optimiser/OptimiserContent.tsx
  website/src/views/optimiser/OptimiserForm.tsx
  website/src/views/optimiser/types.ts
Labels: bug, optimiser

#4105 Add Optimiser Beta toaster
  website/src/storage/keys.ts
  website/src/views/components/notfications/BetaBanner.scss
  website/src/views/components/notfications/BetaBanner.tsx
  website/src/views/settings/BetaToggle.tsx
  website/src/views/settings/SettingsContainer.scss
  website/src/views/timetable/TimetableContent.tsx
Labels: optimiser

#4039 website: Implement random course picker button
  website/src/views/components/searchkit/RandomPicker.tsx
  website/src/views/modules/ModuleFinderSidebar.scss
  website/src/views/modules/ModuleFinderSidebar.tsx
  website/src/views/modules/ModuleRandomButton.scss
  website/src/views/modules/ModuleRandomButton.tsx
Labels: feature request
